### ISSUE TITLE
function RethinkDB.Connection.connect/1 is undefined or private. Did you mean one of: * connect/2

### ISSUE THREAD

**Issue by hugocbp** [almightycouch/rethinkdb_ecto#13]
I'm trying to integrate the adapter into a new Phoenix app (1.2.0), but I get this error whenever I try to start the server:

```
[error] GenServer RethinkPhoenix.Repo.Pool terminating
** (UndefinedFunctionError) function RethinkDB.Connection.connect/1 is undefined or private. Did you mean one of:

      * connect/2

    (rethinkdb) RethinkDB.Connection.connect([name: RethinkPhoenix.Repo.Pool, otp_app: :rethink_phoenix, repo: RethinkPhoenix.Repo, adapter: RethinkDB.Ecto, port: 28015, dat
abase: "rethink_phoenix_dev", hostname: "localhost", pool_size: 10])
    lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: RethinkDB.Connection
```

I believe I've follow the instructions, as this is a brand new app. My mix.exs:

```
 def application do
    [mod: {RethinkPhoenix, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :rethinkdb_ecto]]
  end

defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:rethinkdb, "~> 0.4.0"},
     {:rethinkdb_ecto, "~> 0.5.0"}]
  end
```

And config/dev.exs:

```
config :rethink_phoenix, RethinkPhoenix.Repo,
  adapter: RethinkDB.Ecto,
  port: 28015,
  database: "rethink_phoenix_dev",
  hostname: "localhost",
  pool_size: 10

```

I don't know if I'm doing something wrong here of if it is a bug.``

**Comment by katafrakt** [comment]
@hugocbp This has already been fixed in master, from what I see. If you remove `rethinkdb` dependency from your `mix.exs` and replace `rethinkdb_ecto` with:

```elixir
{:rethinkdb_ecto, github: "almightycouch/rethinkdb_ecto"}
```

it works OK (at least for me).

**Comment by hugocbp** [comment]
Not sure if I'm missing something else, but I created a new app, followed the instructions on the README, changing the version to point to GitHub and still get errors:

```
==> rethink_phoenix
Compiling 12 files (.ex)
warning: function RethinkDB.Ecto.in_transaction?/1 is undefined or private
  lib/rethink_phoenix/repo.ex:2

warning: function RethinkDB.Ecto.rollback/2 is undefined or private
  lib/rethink_phoenix/repo.ex:2

Generated rethink_phoenix app
** (ArgumentError) argument error
    :erlang.process_info(nil, :dictionary)
    (elixir) lib/process.ex:521: Process.info/2
    lib/rethinkdb/connection.ex:210: RethinkDB.Connection.__pool__/1
    lib/rethinkdb/connection.ex:111: RethinkDB.Connection.run/3
    lib/rethinkdb_ecto.ex:150: RethinkDB.Ecto.storage_up/1
    lib/mix/tasks/ecto.create.ex:36: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by katafrakt** [comment]
I deduce your error comes from running `mix ecto.create`, not `mix phoenix.server`, which you describe above. I also have this error with `ecto.create` task, I'll try to have look at that.

**Comment by almightycouch** [comment]
I'm on holliday until September.
Will try to fix that when I'm back.

Sorry for the late answer tought.

**Comment by almightycouch** [comment]
This issue should be fixed in the latest version. Please reopen if this is not the case.
